@startuml
class xcell.geometry.Cylinder {
  center: None
  radius: None
  length: None
  axis: None
}
class xcell.geometry.Disk {
  center: None
  radius: None
  axis: None
  tol: None
}
class xcell.meshes.Mesh {
  bbox: None
  extents: None
  span: None
  center: None
  elements: None
  conductances: None
  elementType: None
  nodeCoords: None
  edges: None
  minl0: None
  indexMap: None
  inverseIdxMap: None
  boundaryNodes: None
}
class xcell.meshes.MeshStats {
  l0Min: None
  l0Max: None
  numEls: None
  numPts: None
  metricCoeffs: None
  metricCoeffNames: None
}
class xcell.meshes.Octant {
  origin: None
  span: None
  center: None
  l0: None
  children: None
  depth: None
  index: None
  vertices: None
  faces: None
  sigma: None
  neighbors: None
  oXYZ: None
}
class xcell.meshes.Octree {
  center: None
  span: None
  maxDepth: None
  bbox: None
  indexMap: None
  inverseIdxMap: None
  changed: None
  tree: None
}
class xcell.nrnutil.LineDataUnits {
  _lw_data: None
}
class xcell.util.Logger {
  name: None
  printout: None
  startWall: None
  start: None
  durationCPU: None
  durationWall: None
  memory: None
}
class xcell.visualizers.CurrentPlot {
  crange: None
  cvals: None
  pts: None
  inset: None
  ax: None
  dim: None
  dim: None
  ax: None
  ax: None
  rElec: None
  iSrc: None
  fullarrow: None
  showInset: None
  showAll: None
  normalAxis: None
  normalCoord: None
  dataScales: None
}
class xcell.visualizers.DataPrefs {
  name: None
  dataSource: None
  scaleStyle: None
  cmap: None
  norm: None
  colors: None
  range: None
  scaleViz: None
  dataViz: None
}
class xcell.visualizers.DisplayPrefs {
  nodePrefs: None
  edgePrefs: None
  imgPrefs: None
}
class xcell.visualizers.ErrorGraph {
  dataScales: None
}
class xcell.visualizers.FigureAnimator {
  fig: None
  study: None
  axes: None
  prefs: None
  prefs: None
  dataSets: None
  dataCat: None
  dataScales: None
}
class xcell.visualizers.LogError {
}
class xcell.visualizers.ScaleRange {
  min: None
  max: None
  knee: None
}
class xcell.visualizers.SingleSlice {
  bnds: None
  tdata: None
  dataSrc: None
  dataScales: None
  timevec: None
}
class xcell.visualizers.SliceSet {
  dataScales: None
}
class xcell.visualizers.SliceViewer {
  fig: None
  ax: None
  ax: None
  fig: None
  sim: None
  nLevels: None
  topoType: None
  prefs: None
  edgeData: None
  nodeData: None
  edgeArtist: None
  nodeArtist: None
  edgeScaleViz: None
  nodeScaleViz: None
}
class xcell.visualizers.SortaLogNorm {
}
class xcell.visualizers.TimingBar {
  maxtime: None
  fig: None
  ax: None
  ax: None
  data: None
}
class xcell.xCell.CurrentSource {
  value: None
  coords: None
  radius: None
}
class xcell.xCell.SimStudy {
  studyPath: None
  nSims: None
  currentSim: None
  bbox: None
  span: None
  center: None
  iSourceCoords: None
  iSourceVals: None
  vSourceCoords: None
  vSourceVals: None
}
class xcell.xCell.Simulation {
  currentSources: None
  voltageSources: None
  vSourceNodes: None
  vSourceVals: None
  nodeRoleTable: None
  nodeRoleVals: None
  mesh: None
  currentTime: None
  iteration: None
  meshnum: None
  stepLogs: None
  stepTime: None
  memUsage: None
  print: None
  nodeVoltages: None
  edges: None
  gMat: None
  RHS: None
  nDoF: None
  name: None
  meshtype: None
  ptPerAxis: None
  asDual: None
}
class xcell.xCell.VoltageSource {
  value: None
  coords: None
  radius: None
}
xcell.meshes.Mesh <|-- xcell.meshes.Octree
xcell.visualizers.FigureAnimator <|-- xcell.visualizers.CurrentPlot
xcell.visualizers.FigureAnimator <|-- xcell.visualizers.ErrorGraph
xcell.visualizers.FigureAnimator <|-- xcell.visualizers.LogError
xcell.visualizers.FigureAnimator <|-- xcell.visualizers.SingleSlice
xcell.visualizers.FigureAnimator <|-- xcell.visualizers.SliceSet
@enduml

