#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  6 17:38:40 2021

@author: benoit
"""

import xCell
import numpy as np

maxdepth=7
print('%d elements'%8**maxdepth)
bbox=np.append(-np.ones(3),np.ones(3))

setup=xCell.Simulation('')
tree=xCell.Octree(bbox,maxdepth)
msh=xCell.Mesh(2*np.ones(3))

def metric(coord):
    return 0

setup.startTiming('refine')
tree.refineByMetric(metric)
setup.logTime()


tree.makeMesh(msh)
